/**
 * feedback.ts — what the system learns every time a person picks a topic.
 *
 * A clarification answered is not just a better answer for that one question.
 * It is a LABELLED PAIR: this wording, that document, confirmed by a human who
 * knew what they meant. Those are exactly the labels this project has been
 * short of — the 76-question benchmark had to be generated by a model and its
 * expected answers turned out to be wrong often enough to matter. Here the
 * labels arrive for free, in real user wording, and they accumulate.
 *
 * Two uses, and the distinction between them is the important part:
 *
 *   ORDERING (on by default). A new question close to a remembered one puts the
 *   remembered document at the top of the topic list. Low risk: it changes
 *   what is OFFERED, and the person still chooses.
 *
 *   CONFIDENCE (off by default). Letting a remembered confirmation satisfy the
 *   refusal gate is a much stronger claim — that a human answered this question
 *   before, so the corpus demonstrably covers it. It is defensible only on a
 *   near-identical question, which is why the similarity bar is high and the
 *   switch is off until there is enough recorded history to measure it. This
 *   project has broken its own refusal guarantee twice by letting a helpful
 *   signal reach the gate; that is not happening a third time by default.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { LOCAL_DATA_DIR, FEEDBACK_ORDERING, FEEDBACK_SIMILARITY } from "./config.js";
import { cosine } from "./retrieve.js";

export interface FeedbackEntry {
  /** The question exactly as it was typed. */
  q: string;
  /** Its embedding, so a later question can be compared without re-embedding. */
  vector: number[];
  /** The documents behind the topic the user chose. Empty = "none of these". */
  codes: string[];
  /** The label the user actually saw and clicked. */
  label: string;
  collection: string;
  at: string;
}

const FILE = () => join(LOCAL_DATA_DIR, "feedback.json");

let cache: FeedbackEntry[] | null = null;

export function loadFeedback(): FeedbackEntry[] {
  if (cache) return cache;
  try {
    cache = existsSync(FILE()) ? JSON.parse(readFileSync(FILE(), "utf-8")) : [];
  } catch {
    // A corrupt feedback file must never take retrieval down with it: this is
    // an optimisation, not a source of truth.
    cache = [];
  }
  return cache!;
}

export function recordChoice(entry: Omit<FeedbackEntry, "at">): void {
  const all = loadFeedback();
  all.push({ ...entry, at: new Date().toISOString() });
  mkdirSync(LOCAL_DATA_DIR, { recursive: true });
  writeFileSync(FILE(), JSON.stringify(all, null, 1));
  cache = all;
}

/**
 * The documents a person previously chose for a question close to this one.
 *
 * "Close" is deliberately strict. A loose match would quietly turn one person's
 * choice into a standing rule for a whole family of questions, which is how a
 * helpful memory becomes a wrong answer that is very hard to trace.
 *
 * A recorded "none of these" (empty codes) is returned as an empty array too,
 * but the caller can tell the difference: `matched` says whether anything was
 * remembered at all.
 */
export function recall(
  vector: number[],
  collection: string,
): { matched: boolean; codes: string[]; similarity: number } {
  if (!FEEDBACK_ORDERING) return { matched: false, codes: [], similarity: 0 };

  let best: { e: FeedbackEntry; s: number } | null = null;
  for (const e of loadFeedback()) {
    if (e.collection !== collection) continue;
    if (e.vector?.length !== vector.length) continue;
    const s = cosine(vector, e.vector);
    if (!best || s > best.s) best = { e, s };
  }
  if (!best || best.s < FEEDBACK_SIMILARITY) return { matched: false, codes: [], similarity: best?.s ?? 0 };
  return { matched: true, codes: best.e.codes, similarity: best.s };
}

/** Everything recorded, for turning real usage into an evaluation set. */
export function exportLabels(): { q: string; codes: string[]; label: string; at: string }[] {
  return loadFeedback().map(({ q, codes, label, at }) => ({ q, codes, label, at }));
}
